[package]
name = "derive_macro"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["proc-macro"]

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
